[package]
name = "spotnet"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.8.2"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.8.2"
ekubo = { git = "https://github.com/ekuboprotocol/abis", rev = "edb6de8" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "8208871" }
openzeppelin = "0.17.0"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.30.0" }

[lib]

[[target.starknet-contract]]

[tool.fmt]
sort-module-level-items = true

[[tool.snforge.fork]]
name = "SEPOLIA"
url = "http://178.32.172.148:6062/v0_7"
block_id.tag = "latest"

[[tool.snforge.fork]]
name = "MAINNET"
url = "http://178.32.172.148:6060/v0_7"
block_id.tag = "latest"
